config/routes.rb
Rails.application.routes.draw do
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/signup', to:"vips#new"
  post '/signup', to:"vips#create"
  get '/denglu', to:"logins#new"
  post '/denglu', to:"logins#create"
  delete '/dengchu', to:"logins#destory"
  get '/edit', to:"vips#edit"

   get '/show', to:'static_pages#show'
   get '/shop', to:'static_pages#shop'
   post '/show', to:'pingluns#create'
   get '/index',to:'pingluns#index'
   delete '/show',to:'pingluns#destroy'

   get'/caiwu', to:'caiwus#new'
   post'/caiwu', to:'caiwus#create'
   get'/caiwus', to:'caiwus#index'

   get'/yuding', to:'yudings#new'
   post'/yuding', to:'yudings#create'
   patch'/yuding', to:'yudings#update'
   get'/yudings', to:"yudings#index"

  
  resources :vips
  resources :pingluns,  only:[:create, :destory]
  resources :caiwus
  resources :yudings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caiwu.rb
class Caiwu < ApplicationRecord
     
end

app/models/pinglun.rb
class Pinglun < ApplicationRecord
  belongs_to :vip
  validates :content, presence: true

  def self.search(search)
    where("content LIKE ?", "%#{search}%")
  end 
   
end

app/models/vip.rb
class Vip < ApplicationRecord
    has_many :pingluns
    has_secure_password
end

app/models/yuding.rb
class Yuding < ApplicationRecord

    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include LoginsHelper
end

app/controllers/caiwus_controller.rb
class CaiwusController < ApplicationController

    def new
      @caiwu = Caiwu.new
      @caiwus = Caiwu.all 
    end    

    def index
       
       @total = Caiwu.sum("jine")
       
       if params[:start_date] 
      
        ddd = params[:end_date][:day]
        eee = ddd.to_i + 1
        aaa= params[:start_date][:year]+"-"+params[:start_date][:month]+"-"+params[:start_date][:day]
        bbb=params[:end_date][:year]+"-"+params[:end_date][:month]+"-"+eee.to_s
        @caiwus = Caiwu.where("created_at>= ? AND created_at<=?", aaa, bbb)
       else
        @caiwus = Caiwu.all
       end
    end


    def create
      @caiwu = Caiwu.new(params.require(:caiwu).permit(:zhuohao, :jine))
      if @caiwu.save
        redirect_to @caiwu
      else
        render 'new'  
      end

    end    
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    vip = Vip.find_by(email:params[:login][:email].downcase)
    if vip && vip.authenticate(params[:login][:password])
      log_in(vip)
      redirect_to root_url
    else
      render 'new'
    end     
    
  end  

  def destory
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end  
end

app/controllers/pingluns_controller.rb
class PinglunsController < ApplicationController

    def index
        @pingluns = Pinglun.paginate(page: params[:page]).order('created_at DESC')
        if params[:search]
            @pingluns = Pinglun.search(params[:search]).order('created_at DESC')
          else
            @pingluns = Pinglun.all.order('created_at DESC')
          end
        
    end    

    def create
        @pinglun = current_user.pingluns.build(pinglun_params)
        
        if @pinglun.save
            redirect_to show_path
        else
            render 'static_pages/home'  
        end   
    end
    
    def destroy
        @pinglun = Pinglun.find_by(params[:vip_id])
        @pinglun.destroy
        redirect_to index_path
    end 
    
    private
       def pinglun_params
        params.require(:pinglun).permit(:content, :status)
       end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
        
        
    end

    def shop
    end    
    
    def show
        @vip = current_user
        
        @pinglun = @vip.pingluns.build

        @pingluns = @vip.pingluns

        
    end    
    
end

app/controllers/vips_controller.rb
class VipsController < ApplicationController
  def new
    @vip = Vip.new
  end

  def create
    @vip = Vip.new(vip_params)
    if @vip.save
      redirect_to @vip
    else
      render 'new'  
    end
  end    

  def show
    @vip = Vip.find(params[:id])
    @pingluns =@vip.pingluns
  end  
   
  def edit
    @vip = Vip.find(params[:id])
    
  end 
   
  def update
    @vip = Vip.find(params[:id])
    
    if @vip.update_attributes(vip_params)
      redirect_to @vip
    else
      render  'edit'  

    end  

  end  

  private
    def vip_params
       params.require(:vip).permit(:name, :email, :password, :password_confirmation)
    end  





end

app/controllers/yudings_controller.rb
class YudingsController < ApplicationController
    def new
        @yuding = Yuding.new
        @yudings = Yuding.all.order('created_at DESC')
    end
    
    
    def create
       @yuding = Yuding.new(yuding_params)
       if @yuding.save
        redirect_to @yuding

       else
        render 'static_pages/home'  

       end
    end 

    def index
        @yudings = Yuding.all.order('created_at DESC')
        @yuding = Yuding.find_by(params[:id])
        @yuding.update_attributes(status: "2")
    end    
    
    def update
        @yuding = Yuding.find_by(id: params[:yuding][:id])
        @yuding.update_attributes(status: "2")
        redirect_to @yuding
        
    end    
    
    private
    def yuding_params
       params.require(:yuding).permit(:zhuohao, :starttime, :endtime, :status)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caiwus_helper.rb
module CaiwusHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
    def log_in(user)
        session[:user_id] = user.id
    end    

    def current_user
        @current_user ||= Vip.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end    

    

end

app/helpers/pingluns_helper.rb
module PinglunsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vips_helper.rb
module VipsHelper
end

app/helpers/yudings_helper.rb
module YudingsHelper
end

app/views/caiwus/_caiwu.html.erb
<ul class="caiwus">

   
<li>
桌号：<%= caiwu.zhuohao %>  金额：<%=caiwu.jine %>元    消费时间: <%= caiwu.created_at.to_time.strftime('%Y-%m-%d %H:%M:%S')%>

</li>

 </ul>

app/views/caiwus/index.html.erb
<%= form_tag("/caiwus", method: "get") do %>
  <h3>开始时间：</h3><%= select_date Date.today, prefix: :start_date %>
  <h3>结束时间：</h3><%= select_date Date.today, prefix: :end_date %>
 
  <%= submit_tag("查 询") %>
<% end %>

<h1>财务明细</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= render @caiwus %>

</div>
</div>

总计：<%= @total %> 元

app/views/caiwus/new.html.erb
<%= form_for @caiwu, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<h3> 桌号</h3>
<%= f.select :zhuohao, [1,2,3,4,5,6]%>
    
<%=f.number_field(:jine) %>
<%= f.submit "提交金额", class: "btn btn-primary" %> 

<% end %>

<%= render @caiwus %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
  <title><%=yield(:title) %> |Welcome to the shop web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
        <header class="navbar navbar-fixed-top navbar-inverse"> 
          <div class="container">
             <%= link_to "首页", root_path, id: "logo" %> <nav>
                <ul class="nav navbar-nav navbar-right">
                     <li><%= link_to "预订", yuding_path %></li>
                     <li><%= link_to "shop展示", shop_path %></li>
                    
                     <button class="btn dropdown-toggle" id="mydropdownmenu" data-toggle="dropdown"> 财务</button>
           
                       <ul class = "dropdown-menu">
                       
                        <li><%= link_to "财务录入", caiwu_path %></li>
                    
                        <li><%= link_to "财务汇总", caiwus_path %></li>
                        
                       </ul>
                     <li><%= link_to "评价", index_path %></li>
                     <% if logged_in? %>
                     <li class ="dropdown" >
                       
                      <button class="btn dropdown-toggle" id="mydropdownmenu" data-toggle="dropdown">用户信息</button>
           
                       <ul class = "dropdown-menu">
                       
                        <li><%= link_to "修改资料", edit_vip_path(current_user) %></li>
                    
                        <li><%= link_to "我的评价", show_path %></li>
                        <li><%= link_to "退出登陆", dengchu_path, method: "delete" %></li>
                       </ul>
                       <% else %>


                         <li><%= link_to "登陆", denglu_path %></li>
                     <% end %>
                </ul> 
              </nav>
           </div>
        </header>

      <div class = 'container' >
          <%= yield %>
      </div>    
  </body>

  </html>

app/views/logins/new.html.erb
<html>
<body>
<% render 'layouts/header' %>
<h1>Log in</h1>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
       <%= form_for(:login, url: denglu_path) do |f| %> 
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.submit "登陆", class: "btn btn-primary" %>
        <% end %>
   </div>
</div>
</body>
</html>

app/views/pingluns/_pinglun.html.erb
<li>

<span class="user"><%= link_to pinglun.vip.name, pinglun.vip %></span> 
<span class="content"><%= pinglun.content %></span>


<% if pinglun.status == 3%>
        <%  bbb = "中评" %>
    <% elsif   pinglun.status == 4%>
      <%  bbb="差评"%>
      <% else   pinglun.status == 2%>
      <%  bbb="好评"%>
      <% end  %>
 
<span class="jibie"><%=bbb%></span>
<span class="shanchu">
<%= link_to "删除", show_path, :confirm =>"确定？", :method =>:delete %>
</span>






</li>

app/views/pingluns/index.html.erb
<%= form_tag("/index", method: "get") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag("查找") %>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= render @pingluns   %>

</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "首页") %> 



<div class="center jumbotron">
 <h1>Welcome to the SHOP!</h1>

<%= link_to "注册", signup_path, class: "btn btn-lg btn-primary" %> 
</div>

<ul class="list-group">
   <li class="list-group-item list-group-item-success">餐厅介绍</li>
</ul>
<div class="row" align="center" >
    <div class="col-sm-4 col-md-4">
      <div class="center-block">
      <img src="assets/cc1.jpeg" alt="..." width="150" height="100";>
        <div class="caption">
            <h3 align="center"><big>生日聚会</big></h3>
        <p align="center">与小伙伴们举行party</p>
        <p align="center"><a href="/yuding" class="btn btn-primary" role="button">开始预订</a></p>
        </div>
      </div>
    </div>

    <div  align="center" class="col-sm-4 col-md-4">
      <div class="center-block">
       <img src="assets/cc2.jpeg" alt="..." width="150" height="100";>
        <div class="caption">
        <h3 align="center">家人聚会</h3>
        <p>与家人享受美味时刻</p>
        <p align="center"><a href="/yuding" class="btn btn-primary" role="button">开始预订</a></p>
       </div>
       </div>
    </div>
   
  <div class="col-sm-4 col-md-4">
    <div class="center-block">
      <img src="assets/cc3.jpeg" alt="..."width="150" height="100"; >
      <div class="caption">
        <h3 align="center">老友相聚</h3>
        <p align="center">老友时常相伴</p>
        <p align="center" ><a href="/yuding" class="btn btn-primary" role="button">开始预订</a></p>
      </div>
    </div>
    </div>

app/views/static_pages/shop.html.erb
<p class="bg-success">A 区</p>
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct4.jpg" alt="...">
        <div class="caption">
          
          <h3>桌号1</h3>
          
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct5.jpg" alt="...">
        <div class="caption">
          <h3>桌号2</h3>
          
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct6.jpg" alt="...">
        <div class="caption">
          <h3>桌号3</h3>
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
</div>
<p class="bg-success">B 区</p>
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct7.jpg" alt="...">
        <div class="caption">
          <h3>桌号4</h3>
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct8.jpg" alt="...">
        <div class="caption">
          <h3>桌号5</h3>
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <img src="assets/ct9.jpg" alt="...">
        <div class="caption">
          <h3>桌号6</h3>
          
          <p><a href="/yuding" class="btn btn-primary" role="button">预约</a> </p>
        </div>
    </div>
  </div>
</div>

app/views/static_pages/show.html.erb
<% provide(:title, @vip.name) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@pinglun, url:pingluns_path) do |f| %>
    <div class="field">
       <%= f.text_area :content, placeholder: "发表评论..." %> 
       </div>

       <div class ="status">
       <li><%= f.radio_button :status, value='2'%>好评</li>
       <li><%= f.radio_button :status, value='3'%>中评</li>
       <li><%= f.radio_button :status, value='4'%>差评</li>

       
       </div>
       <%= f.submit "发布", class: "btn btn-primary" %> 
       <% end %>


       </div>
</div>



<h4>评论总数<%= @vip.pingluns.count %> </h4>

<%= render @pingluns %> 

app/views/vips/edit.html.erb
<h1>修改资料</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for(@vip) do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name %>

     <%= f.label :email %>
     <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

       <%= f.submit "确认修改个人资料", class: "btn btn-primary" %> 
       <% end %>
    </div>
</div>

app/views/vips/new.html.erb
<h1>注册</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for(@vip, url:signup_path) do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name %>

     <%= f.label :email %>
     <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

       <%= f.submit "确认注册", class: "btn btn-primary" %> 
       <% end %>
    </div>
</div>

app/views/vips/show.html.erb
<% provide(:title, @vip.name) %>
注册邮箱：<%= @vip.email %>
注册用户名：<%= @vip.name %>
<%= render @pingluns %>

app/views/yudings/_yuding.html.erb
    <% if yuding.status == 1  %>
      <%   bbb = "已预订" %>
      <%   else  %>
        <% bbb = "已取消"  %>
        <% end %>
       
    
    
       
  <li>桌号：<%=yuding.zhuohao %> 预定时间:<%=yuding.starttime %>-<%=yuding.endtime %>状态:<%=bbb%>
  操作:<%= form_for(@yuding, :url => { :controller=>"yudings",:action => "update"},method: "patch") do |f|%>
    <%= f.hidden_field(:id, :value=>"#{yuding.id}") %>
    <%= f.submit("取消")%>
    <% end %>
</li>

  

app/views/yudings/index.html.erb
    
       
 <%= render @yudings %>

app/views/yudings/new.html.erb
<h1> 预订</h1>
<%= form_for(@yuding, method: "post") do |f|%>
  
    <%= f.select(:zhuohao, [1,2,3,4,5,6]) %>

    开始时间：
    
    <%= f.datetime_select  :starttime%>
    结束时间：
    <%= f.datetime_select  :endtime%>
    <%= f.hidden_field(:status, :value=>"1") %>
    <%= f.submit("预订") %>
    <% end %>

  <div>
    <%= render @yudings %>
</div>